# -*- coding: utf-8 -*-
"""Worksheet3_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kD-w0TJQr75p28J3oOkdJckGVbhdn_fu
"""

import numpy as np

def softmax(z):
    z = np.array(z)
    z_stable = z - np.max(z, axis=-1, keepdims=True)
    exp_z = np.exp(z_stable)
    sum_exp = np.sum(exp_z, axis=-1, keepdims=True)
    return exp_z / sum_exp

def predict(z):
    probabilities = softmax(z)
    return np.argmax(probabilities, axis=-1)

z = [2.0, 1.0, 0.1]

probs = softmax(z)
print("Probabilities:", probs)

pred = predict(z)
print("Predicted class:", pred)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def load_and_prepare_mnist(csv_path, test_size=0.2, normalize=True):
    df = pd.read_csv('/content/mnist.csv')
    y = df.iloc[:, 0].values
    X = df.iloc[:, 1:].values
    if normalize:
        X = X / 255.0
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=42, stratify=y
    )
    return X_train, X_test, y_train, y_test

import matplotlib.pyplot as plt

def plot_sample_images(X, y):
    plt.figure(figsize=(10, 5))
    plotted = set()

    for i in range(len(y)):
        label = y[i]

        if label not in plotted:
            plt.subplot(2, 5, label + 1)
            image = X[i].reshape(28, 28)

            plt.imshow(image, cmap='gray')
            plt.title(f"Digit: {label}")
            plt.axis('off')

            plotted.add(label)
        if len(plotted) == 10:
            break

    plt.tight_layout()
    plt.show()

X_train, X_test, y_train, y_test = load_and_prepare_mnist("/content/mnist.csv")
plot_sample_images(X_train, y_train)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification, make_circles
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Set random seed for reproducibility
np.random.seed(42)

X_linear_separable, y_linear_separable = make_classification(
    n_samples=200,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_clusters_per_class=1,
    random_state=42
)

# Split dataset
X_train_linear, X_test_linear, y_train_linear, y_test_linear = train_test_split(
    X_linear_separable, y_linear_separable,
    test_size=0.2,
    random_state=42
)

# Train logistic regression
logistic_model_linear_separable = LogisticRegression()
logistic_model_linear_separable.fit(X_train_linear, y_train_linear)

X_non_linear_separable, y_non_linear_separable = make_circles(
    n_samples=200,
    noise=0.1,
    factor=0.5,
    random_state=42
)

# Split dataset
X_train_non_linear, X_test_non_linear, y_train_non_linear, y_test_non_linear = train_test_split(
    X_non_linear_separable, y_non_linear_separable,
    test_size=0.2,
    random_state=42
)

# Train logistic regression
logistic_model_non_linear_separable = LogisticRegression()
logistic_model_non_linear_separable.fit(X_train_non_linear, y_train_non_linear)

def plot_decision_boundary(ax, model, X, y, title):
    h = 0.02

    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    xx, yy = np.meshgrid(
        np.arange(x_min, x_max, h),
        np.arange(y_min, y_max, h)
    )

    Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    ax.contourf(xx, yy, Z, alpha=0.8, cmap=plt.cm.Paired)
    ax.scatter(X[:, 0], X[:, 1], c=y, edgecolors='k', cmap=plt.cm.Paired)

    ax.set_title(title)
    ax.set_xlabel("Feature 1")
    ax.set_ylabel("Feature 2")

fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Linearly separable (train)
plot_decision_boundary(
    axes[0, 0],
    logistic_model_linear_separable,
    X_train_linear,
    y_train_linear,
    "Linearly Separable Data (Training)"
)

# Linearly separable (test)
plot_decision_boundary(
    axes[0, 1],
    logistic_model_linear_separable,
    X_test_linear,
    y_test_linear,
    "Linearly Separable Data (Testing)"
)

# Non-linear (train)
plot_decision_boundary(
    axes[1, 0],
    logistic_model_non_linear_separable,
    X_train_non_linear,
    y_train_non_linear,
    "Non-Linearly Separable Data (Training)"
)

# Non-linear (test)
plot_decision_boundary(
    axes[1, 1],
    logistic_model_non_linear_separable,
    X_test_non_linear,
    y_test_non_linear,
    "Non-Linearly Separable Data (Testing)"
)

plt.tight_layout()

# Save and show
plt.savefig("decision_boundaries.png")
plt.show()